### ISSUE TITLE
Want to show more than one button in a cell

### ISSUE THREAD

**Issue by vishumunjal1234** [pradeep7may/PKSwipeTableViewCell#3]
Current i am doing this : -

        
        //Create a view that will display when user swipe the cell in right
        let viewCall = UIView()
        let viewCall2 = UIView()

        viewCall.backgroundColor = UIColor.blue
        viewCall.frame = CGRect(x: 0, y: 0,width: (self.frame.height)*3/4,height: self.frame.height)
        viewCall2.backgroundColor = UIColor.blue
        viewCall2.frame = CGRect(x: 0, y: 0,width: (self.frame.height)*3/4,height: self.frame.height)

        //Add a label to display the call text
        let lblCall = UILabel()
        let lblCall2 = UILabel()
        lblCall2.text  = "Calllllllll"

        lblCall.text  = "Call"
        lblCall.font = UIFont.systemFont(ofSize: 15.0)
        lblCall.textColor = UIColor.white
        lblCall.textAlignment = NSTextAlignment.center
        lblCall.frame = CGRect(x: 0,y: self.frame.height - 30,width: viewCall.frame.size.width,height: 30)
         
        //Add a button to perform the action when user will tap on call and add a image to display
        let btnCall = UIButton(type: UIButtonType.custom)
        btnCall.frame = CGRect(x: (viewCall.frame.size.width - 40)/2,y: 5,width: 40,height: 40)
        btnCall.setImage(UIImage(named: "navigation"), for: UIControlState())
        btnCall.addTarget(self, action: #selector(CurrentOrderTableViewCell.callButtonClicked), for: UIControlEvents.touchUpInside)
        btnCall.center = viewCall.center

        viewCall.addSubview(btnCall)
        viewCall.addSubview(lblCall)
        viewCall2.addSubview(btnCall)
        viewCall2.addSubview(lblCall)

        //Call the super addRightOptions to set the view that will display while swiping
        super.addRightOptionsView(viewCall)
        super.addRightOptionsView(viewCall2)

**Comment by pradeep7may** [comment]
Hi,

If you want to display more than 1 view then you have to combined all your subviews in one view then you can pass that view in super.addRightOptionsView(). You don't need to call super.addRightOptionsView()  twice.

From your code create a parent uiview and add both viewCall and viewCall2 as subview then pass the parentView in super.addRightOptionsView(parentView).

Let me know if you face any issues.

Thanks,
Pradeep

**Comment by vishumunjal1234** [comment]
Hi pradeep,
I am not able  to set the button .
Please find the code and the respective screenshot for the same .
![img_0035](https://user-images.githubusercontent.com/5224975/27542515-12c63dce-5aa5-11e7-8ddb-caf551885583.PNG)
    
        let mainView = UIView()
        mainView.translatesAutoresizingMaskIntoConstraints = false
        mainView.frame = CGRect(x: 0, y: 0,width: (self.frame.height),height: self.frame.height)
        

        //Create a view that will display when user swipe the cell in right
        let viewCall = UIView()
        let viewCall2 = UIView()

        viewCall.backgroundColor = UIColor.darkPinkCustomColor()
        viewCall2.backgroundColor = UIColor.red

        viewCall.frame = CGRect(x: 0, y: 0,width: (mainView.frame.height)*3/4,height: self.frame.height)
        viewCall2.frame = CGRect(x: 0, y: 0,width: (mainView.frame.height)/2,height: self.frame.height)

        //Add a label to display the call text
        let lblCall = UILabel()
        lblCall.text  = "Call"
        lblCall.font = UIFont.systemFont(ofSize: 15.0)
        lblCall.textColor = UIColor.white
        lblCall.textAlignment = NSTextAlignment.center
        lblCall.frame = CGRect(x: 0,y: self.frame.height - 30,width: viewCall.frame.size.width,height: 30)
        //Add a button to perform the action when user will tap on call and add a image to display
        let btnCall = UIButton(type: UIButtonType.custom)
        btnCall.frame = CGRect(x: (viewCall.frame.size.width - 40)/2,y: 5,width: 40,height: 40)
        btnCall.setImage(UIImage(named: "call"), for: UIControlState())
        btnCall.addTarget(self, action: #selector(CurrentOrderTableViewCell.callButtonClicked), for: UIControlEvents.touchUpInside)
        btnCall.center = viewCall.center
        viewCall.addSubview(btnCall)
        viewCall.addSubview(lblCall)
        mainView.addSubview(viewCall)
        mainView.addSubview(viewCall2)

        //Call the super addRightOptions to set the view that will display while swiping
        super.addRightOptionsView(mainView)

**Comment by pradeep7may** [comment]
Hi,

It seems your views are overlapping as started from same x and y. 

 viewCall.frame = CGRect(x: 0, y: 0,width: (mainView.frame.height)*3/4,height: self.frame.height)
  viewCall2.frame = CGRect(x: 0, y: 0,width: (mainView.frame.height)/2,height: self.frame.height)

Please check the frames of those views.

Also, if you can make a dummy project and send it to me then It will be better for me to check the issue that you are facing.

Thanks,
Pradeep
